---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
  namespace: emojivoto-staging
spec:
  type: ClusterIP
  selector:
    app: web-svc
  ports:
  - name: http
    port: 80
    targetPort: 8080