apiVersion: v1
kind: Service
metadata:
  annotations:
    ### Issues page on application repository
    a8r.io/bugs: https://github.com/aes-t2/sol-eng-emojivoto/issues
    ### Opens slack and shows Casey's slack profile
    a8r.io/chat: https://datawire.slack.com/team/U0120PU7P7S
    a8r.io/dependencies: emoji-svc.emojivoto, voting-svc.emojivoto
    a8r.io/description: gRPC API for voting and leaderboard
    ### Goes to the Ambassdor docs homepage
    a8r.io/documentation: https://www.getambassador.io/docs/latest/
    ### REQUIRES LOGIN: Datadog incident panel (Only shows demo screen)
    a8r.io/incidents: https://app.datadoghq.com/incidents/settings
    ### REQUIRES LOGIN: Datadog log aggregation panel (Only shows demo screen)
    a8r.io/logs: https://app.datadoghq.com/logs/activation
    a8r.io/owner: "@cakuros"
    ### REQUIRES LOGIN (admin:prom-operator): Argo Rollouts Grafana dashboard
    a8r.io/performance: https://obs.linkerd.amb-labs.io/grafana/d/fDNtJHg7k/argo-rollouts?orgId=1&refresh=5s
    ### Emojivoto repository
    a8r.io/repository: https://github.com/aes-t2/sol-eng-emojivoto
    ### Ambassador docs debugging page
    a8r.io/runbook: https://www.getambassador.io/docs/latest/topics/running/debugging/
    ### Ambassador support webpage
    a8r.io/support: https://support.datawire.io/hc/en-us
    ### Linkerd emojivoto web pod Grafana dashboard
    a8r.io/uptime: https://linkerd.amb-labs.io/grafana/d/linkerd-pod/linkerd-pod?orgId=1&refresh=1m&var-namespace=emojivoto&var-pod=web-755775fdf7-bh5jz&var-deployment=&var-inbound=All&var-outbound=All
    a8r.io/rollouts.scm.branch: "main"
    a8r.io/rollouts.scm.path: "yaml/emoji-web"
    a8r.io/rollouts.image-repo.type: "dockerhub"
    a8r.io/rollouts.image-repo.name: "caseykurosawa/emojivoto-web"
    a8r.io/rollouts.deployment: "web"
    a8r.io/rollouts.mappings: "emojivoto-mapping"
  name: web-svc
  namespace: emojivoto
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web-svc
