apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    getambassador.io/rolloutId: 18a0cd08-9de5-4395-82c4-165122765ec2
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v11
  name: web
  namespace: emojivoto
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-svc
      version: v11
  strategy:
    canary:
      canaryService: web-svc-canary
      stableService: web-svc
      steps:
      - setWeight: 70
      - pause:
          duration: 300
      trafficRouting:
        ambassador:
          mappings:
          - emojivoto-mapping
  template:
    metadata:
      annotations:
        telepresence.getambassador.io/inject-traffic-agent: enabled
      creationTimestamp: null
      labels:
        app: web-svc
        version: v11
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "8080"
        - name: EMOJISVC_HOST
          value: emoji-svc.emojivoto:8080
        - name: VOTINGSVC_HOST
          value: voting-svc.emojivoto:8080
        - name: INDEX_BUNDLE
          value: dist/index_bundle.js
        image: caseykurosawa/emojivoto-web:v12
        name: web-svc
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
      serviceAccountName: web
status:
  blueGreen: {}
  canary: {}
