#solutions-eng-linkerd
#uid=91572450-32a3-40a6-850e-83d5635f68d4
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJXRENCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFl5TURZMU5UZ3lOakFlRncweU1UQTFNVEF4TkRFd01qWmFGdzB6TVRBMU1EZ3hOREV3TWpaYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFl5TURZMU5UZ3lOakJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQk42WXhZN2V6QmhibUJIUHZFQjBaTys2dHViU3BSSEc5aFNKd0dRWHdTaG4KZUhxSkdNV2xsaE5qOHR5WkoyOXZxajVXdDRVa2Nyd1RGMHFDdGt3azJxdWpJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDWnhGbjFxWHlzCmljZmp3ZTkxTUNULzB2QncwQk5hakc2N1NlcEpkVE9sVkFJaEFObm1qcGorMWlGbWJSNkkzcDdRNkNLRVBqUVYKdWhEdnp2ODNWekFBWisxWAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://34.121.254.66
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: 1fc93d614fe9737fe18b8fc53e1c9464
    username: admin
